# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Version of the EDF API library
#' @description Returns version of the EDF API library used to interface an EDF file.
#' @export
#' @examples
#' edfR::library_version()
library_version <- function() {
    .Call('_edfR_library_version', PACKAGE = 'edfR')
}

#' Reads preamble of the EDF file.
#'
#' @title Reads preamble of the EDF file.
#' @description Reads preamble of the EDF file.
#' @return string with the preamble
#' @export
#' @examples
#' read_preamble(system.file("extdata", "example.edf", package = "edfR"))
read_preamble <- function(filename) {
    .Call('_edfR_read_preamble', PACKAGE = 'edfR', filename)
}

#' Internal funciton that reads EDF file
#'
#' @title Internal funciton that reads EDF file
#' @description Reads EDF file into a list that contains events, samples, and recordings.
#' DO NOT call this function directly. Instead, use read_edf function that implements
#' parameter checks and additional postprocessing.
#' @param std::string filename, full name of the EDF file
#' @param int consistency, consistency check control (for the time stamps of the start
#' and end events, etc). 0, no consistency check. 1, check consistency and report.
#' 2, check consistency and fix.
#' @param bool import_events, load/skip loading events.
#' @param bool import_recordings, load/skip loading recordings.
#' @param bool import_samples, load/skip loading of samples.
#' @param LogicalVector sample_attr_flag, boolean vector that indicates which sample fields are to be stored
#' @param std::string start_marker_string, event that marks trial start. Defaults to "TRIALID", if empty.
#' @param std::string end_marker_string, event that marks trial end
#' @param NumericVector pixels_per_degree, pixels per degree for the screen that was used for the recording
#' positive values overwrite rx and ry fields' values from the file
#' @return List, contents of the EDF file. Please see read_edf for details.
read_edf_file <- function(filename, consistency, import_events, import_recordings, import_samples, sample_attr_flag, start_marker_string, end_marker_string, pixels_per_degree) {
    .Call('_edfR_read_edf_file', PACKAGE = 'edfR', filename, consistency, import_events, import_recordings, import_samples, sample_attr_flag, start_marker_string, end_marker_string, pixels_per_degree)
}

